TVE_EXPAND = 0x0002
FALSE = 0
TRUE = 1
GL_POINTS = 0x0000
GL_LINES = 0x0001
GL_LINE_LOOP = 0x0002
GL_LINE_STRIP = 0x0003
GL_TRIANGLES = 0x0004
GL_TRIANGLE_STRIP = 0x0005
GL_TRIANGLE_FAN = 0x0006
GL_QUADS = 0x0007
GL_QUAD_STRIP = 0x0008
GL_POLYGON = 0x0009
GL_COMPILE = 0x1300

# Constants for Vertex Arrays
GL_VERTEX_ARRAY = 0x8074
GL_COLOR_ARRAY = 0x8076
GL_FLOAT = 0x1406

OBJECT_TREE_ROOT_TITLE = "Object Demo"
OBJECT_TREE_LEAF_PATTERN_TITLE = "Object Pattern Demo"
OBJECT_3D_TREE_ROOT_TITLE = "3D Object Demo"
OBJECT_3D_TREE_LEAF_PATTERN_TITLE = "Object Pattern Demo"

MECHANICS_TREE_ROOT_TITLE = "Physics"
MECHANICS_TREE_SIMPLE_PENDULUM_TITLE = "Simple Pendulum"
MECHANICS_TREE_PROJECTILE_MOTION_TITLE = "Projectile Motion"
MECHANICS_TREE_PLANETORY_MOTION_TITLE = "Planetory Motion"

PENDULUM_PROPERTIES_TITLE = "Select Pendulum | Properties"
PENDULUM_LENGTH = "Pendulum Length"
PENDULUM_BOB_RADIUS = "Bob Radius"
PENDULUM_BOB_MASS="Mass of Bob"
PENDULUM_AMPITUDE = "Amplitude"
PENDULUM_COLOR_TITLE = "Select Background Color"
PENDULUM_MAX_SWING_ANGLE = "Max Swing Angle"

OBJECT_PROPERTIES_TITLE = "Select Object | Properties"
OBJECT_TYPE_TITLE = "Select The Object Type"
OBJECT_COLOR_TITLE = "Select Background Color"
OBJECT_SIMULATION_PATTERN_TITLE = "Simulation Pattern"
OBJECT_SIMULATION_INTERVAL_TITLE = "Simulation Interval"

OBJECT_TYPES = "Cube,Ball,Pyramid,Aeroplane,Clock,Tower of Hanoi Solver"
OBJECT_TYPE_CUBE = "Cube"
OBJECT_TYPE_BALL = "Ball"
OBJECT_TYPE_PYRAMID = "Pyramid"
OBJECT_TYPE_AEROPLANE = "Aeroplane"
OBJECT_TYPE_CLOCK = "Clock"
OBJECT_TYPE_TOWEROFHANOI = "Tower of Hanoi Solver"

OBJECT_PATTERN_TYPES = "Rotate,Random Movement"
OBJECT_PATTERN_TYPE_ROTATE = "Rotate"
OBJECT_PATTERN_TYPE_RANDOM = "Random Movement"

TOWEROFHANOI_PROPERTIES_TITLE = "Tower of Hanoi | Properties"
TOWEROFHANOI_RINGS_TITLE = "Number of Rings"
TOWEROFHANOI_SPEED_TITLE = "Animation Speed"
TOWEROFHANOI_SPEED_OPTIONS = "0.25,0.50,0.75,1.00,1.25,1.50,1.75,2.00"

PY_SAMPLE_EXPERIMENT_TYPE_GROUP_1_PROPERTIES = "Experiment Group 1 Properties"
PY_SAMPLE_DOC_SETTINGS_KEY = "Py.Sample.Addin.Settings"
PY_SAMPLE_MAIN_EXPERIMENT_NAME = "TowerOfHanoiPy Experiment Simulation Demo"
PY_SAMPLE_EXPERIMENT_TYPE_GROUP_1 = "Experiment Group 1"